version: 0.0
os: linux

files:
  - source: target/edu.tlu-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/restart.sh
      timeout: 300
      runas: ec2-user