version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven dependencies"
      - mvn clean install -DskipTests
  pre_build:
    commands:
      - echo "Running unit tests"
      - mvn test
  build:
    commands:
      - echo "Building Spring Boot application"
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - target/*.jar
